[https://uc-r.github.io/hc_clustering](https://uc-r.github.io/hc_clustering)
[http://www.sthda.com/english/wiki/factoextra-r-package-easy-multivariate-data-analyses-and-elegant-visualization](http://www.sthda.com/english/wiki/factoextra-r-package-easy-multivariate-data-analyses-and-elegant-visualization)

```{r}
library(cluster)
library(ggdendro)
library(factoextra)
library(dendextend)
```

```{r}
load("data/processed/dataframes.RData")
dfX <- 
  df %>% 
  select(-id) %>% 
  select(-starts_with("PCB")) %>% 
  na.omit() %>% 
  droplevels()
mat <- 
  model.matrix(~ - 1 + ., data = dfX) %>% 
  scale()
dim(mat)
dfNonMissing <- 
  df %>% 
  na.omit()
```

```{r}
mat %>% fviz_nbclust(FUN = hcut, k.max = 30, method = "wss")
mat %>% fviz_nbclust(FUN = hcut, k.max = 10, method = "silhouette")
mat %>% fviz_nbclust(FUN = hcut, k.max = 10, method = "gap_stat", nboot = 50)
mat %>% get_dist(method = "euclidean") %>% fviz_dist()
mat %>% get_dist(method = "manhattan") %>% fviz_dist()
mat %>% get_dist(method = "maximum") %>% fviz_dist()
k <- 8
pal <- brewer.pal(k, "Set1")
# pal <- lacroix_palette("PommeBaya", type = "discrete")
```


## K-means clustering

```{r kmeans}
mat %>% fviz_nbclust(FUN = kmeans, k.max = 20, method = "wss")
k <- 2
km <- kmeans(mat, k)
km %>% .$cluster %>% table()
km %>% 
  fviz_cluster(data = mat, 
               palette = pal, 
               labelsize = 8, 
               ellipse.type = "none",
               star.plot = TRUE) + 
  ggtitle("K-means clustering") +
  theme(panel.grid.minor = element_blank())
long <-
  km$centers %>% 
  data.frame() %>%
  mutate(cluster = 1:k) %>%
  gather(var, value, -cluster)
merge(long %>% filter(cluster == 1) %>% select(-cluster) %>% rename(cluster = value),
      long %>% filter(cluster == 2) %>% select(-cluster) %>% rename(cluster = value),
      by = c("var"),
      suffixes = c("1", "2")) %>%
  kable()
```


## PAM

```{r pam}
mat %>% fviz_nbclust(FUN = cluster::pam, method = "silhouette")
k <- 2
pam <- pam(mat, k, metric = "euclidean", stand = FALSE)
pam %>% .$cluster %>% table()
pam %>% 
  fviz_cluster(data = mat, 
               palette = pal, 
               labelsize = 8, 
               ellipse.type = "none",
               star.plot = TRUE) + 
  ggtitle("PAM") +
  theme(panel.grid.minor = element_blank())
long <-
  pam$medoids %>% 
  data.frame() %>%
  mutate(cluster = 1:k) %>%
  gather(var, value, -cluster)
merge(long %>% filter(cluster == 1) %>% select(-cluster) %>% rename(cluster = value),
      long %>% filter(cluster == 2) %>% select(-cluster) %>% rename(cluster = value),
      by = c("var"),
      suffixes = c("1", "2")) %>%
  kable()
```


## Hierarchical clustering

```{r hclust}
hcHClust <- 
  mat %>% 
  hcut(k = k, hc_func = "hclust", hc_method = "ward.D2", hc_metric = "euclidean")
hcHClust %>% .$cluster %>% table()
hcHClust %>% fviz_cluster(palette = pal, labelsize = 8, ggtheme = theme_minimal())
hcHClust %>% fviz_dend(rect = TRUE, cex = 0.5, k_colors = pal)
hcHClust %>% fviz_silhouette(palette = pal, ggtheme = theme_minimal())
```


## Agglomerative hierarchical clustering

```{r agnes}
hcAgnes <- 
  mat %>% 
  hcut(k = k, hc_func = "agnes", hc_method = "ward.D2", hc_metric = "euclidean", stand = TRUE)
ac <- sprintf("Agglomerative coefficient = %.03f (%s method)", hcAgnes$ac, hcAgnes$method)
ac %>% message()
hcAgnes %>% .$cluster %>% table()
hcAgnes %>% fviz_cluster(palette = pal, labelsize = 8, ggtheme = theme_minimal(), main = ac)
hcAgnes %>% fviz_dend(rect = TRUE, cex = 0.5, k_colors = pal, main = ac)
hcAgnes %>% fviz_silhouette(palette = pal, ggtheme = theme_minimal())
```


## Divisive hierarchical clustering

```{r diana}
hcDiana <- 
  mat %>% 
  hcut(k = k, hc_func = "diana", isdiss = FALSE, scaled = TRUE)
ac <- sprintf("Divisive coefficient = %.03f", hcDiana$dc)
ac %>% message()
hcDiana %>% .$cluster %>% table()
hcDiana %>% fviz_cluster(palette = pal, labelsize = 8, ggtheme = theme_minimal(), main = ac)
hcDiana %>% fviz_dend(rect = TRUE, cex = 0.5, k_colors = pal, main = ac)
hcDiana %>% fviz_silhouette(palette = pal, ggtheme = theme_minimal())            
```


## Compare

```{r tanglegram}
dendlist(as.dendrogram(hcAgnes), as.dendrogram(hcDiana)) %>% 
  tanglegram(main_left = "Agnes",
             main_right = "Diana",
             common_subtrees_color_branches = TRUE)
```
