# Model PCB3


## Total PCB3

Prediction model for `PCB3_Total`.

Train model over the tuning parameters.

```{r PCB3_Total_Training}
cl <- makeCluster(cores)
registerDoParallel(cl)
trainingModel <-
  dfTrainPreProc %>% 
  select(-c(id, PCB1_Total, PCB1_CondEmot, PCB1_DevHab, PCB2_Tot, PCB3_PCPonly, PCB3_Person, PCB3_Resource)) %>% 
  train(PCB3_Total ~ ., data = ., method = method, trControl = ctrl, tuneGrid = grid, na.action = na.exclude)
stopCluster(cl)
trainingModel
trainingModel %>% 
  .$results %>% 
  mutate(degree = factor(degree)) %>% 
  ggplot() + 
  aes(x = nprune, y = RMSE, color = degree, group = degree) +
  geom_line() +
  geom_point() +
  theme_bw()
save(trainingModel, file = "output/PCB3_Total_Training.RData")
```

```{r PCB3_Total_Training-varImp}
imp <- varImp(trainingModel)
n <- imp[["importance"]] %>% filter(Overall > 0) %>% nrow()
plot(imp, top = n)
imp[["importance"]] %>% 
  mutate(variable = row.names(.)) %>% 
  filter(Overall > 0) %>% 
  select(variable, Overall) %>%
  kable()
```

```{r PCB3_Tot_Training-finalModel, eval = FALSE}
M <- trainingModel[["finalModel"]]
summary(M)
plot(M)
evimp(M)
plotmo(M)
```

```{r PCB3_Total_Training-predict}
dfTrainPred <- 
  dfTrainPreProc %>% 
  mutate(hat = predict(trainingModel, dfTrainPreProc, na.action = na.pass) %>% as.numeric())
postResample(pred = dfTrainPred$hat, obs = dfTrainPred$PCB3_Total)
cor(dfTrainPred %>% select(PCB3_Total, hat), use = "complete.obs")
dfTrainPred %>% 
  ggplot() +
  ggtitle(sprintf("Correlation = %.03f", cor(dfTrainPred %>% select(PCB3_Total, hat), use = "complete.obs") %>% .[1, 2])) +
  aes(x = hat, y = PCB3_Total) +
  geom_abline(slope = 1, intercept = 0) +
  geom_smooth(method = "lm", formula = y ~ x - 1, color = rgb(0, 0, 1, 0.5), se = FALSE) +
  geom_smooth(method = "lm", formula = y ~ x, color = rgb(1, 0, 0, 0.5), se = FALSE) +
  geom_point(alpha = 1/2)
```

Evaluate model on the validation sample.

```{r PCB3_TotalValidation-predict}
dfValidPred <- 
  dfValid %>% 
  select(-c(id, PCB1_Total, PCB1_CondEmot, PCB1_DevHab, PCB2_Tot, PCB3_PCPonly, PCB3_Person, PCB3_Resource)) %>% 
  select(-one_of(nzv$varname)) %>%
  filter(complete.cases(.)) %>% 
  predict(preProc, .) %>% 
  mutate(hat = predict(trainingModel, ., na.action = na.pass) %>% as.numeric())
postResample(pred = dfValidPred$hat, obs = dfValidPred$PCB3_Total)
cor(dfValidPred %>% select(PCB3_Total, hat), use = "complete.obs")
dfValidPred %>% 
  ggplot() +
  ggtitle(sprintf("Correlation = %.03f", cor(dfValidPred %>% select(PCB3_Total, hat), use = "complete.obs") %>% .[1, 2])) +
  aes(x = hat, y = PCB3_Total) +
  geom_abline(slope = 1, intercept = 0) +
  geom_smooth(method = "lm", formula = y ~ x - 1, color = rgb(0, 0, 1, 0.5), se = FALSE) +
  geom_smooth(method = "lm", formula = y ~ x, color = rgb(1, 0, 0, 0.5), se = FALSE) +
  geom_point(alpha = 1/2)
```
